CONSUMER_CONFIG:
  CLASS: apf.consumers.KafkaSchemalessConsumer
  PARAMS:
    auto.offset.reset: beginning
    bootstrap.servers: b-2-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-1-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-3-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196
    enable.partition.eof: false
    group.id: lsst-test-features-34xxx
    sasl.mechanism: SCRAM-SHA-512
    sasl.password: bigsnexplosion3000
    sasl.username: alerce
    security.protocol: SASL_SSL
    max.poll.interval.ms: 3000000
  SCHEMA_PATH: /home/alerce/Desktop/repos2/pipeline/schemas/correction_ms_step/lsst/output2.avsc
  TOPICS:
  - features_multisurvey
  consume.messages: 1
  consume.timeout: 10
#PRODUCER_CONFIG:
#  CLASS: apf.producers.KafkaSchemalessProducer
#  PARAMS:
#    bootstrap.servers: b-2-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-1-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-3-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196
#    sasl.mechanisms: SCRAM-SHA-512
#    sasl.password: features_msx
#    sasl.username: features_ms
#    security.protocol: SASL_SSL
#  SCHEMA_PATH: /schemas/feature_ms_step/lsst/output.avsc
#  TOPIC: features_multisurvey
FEATURE_FLAGS:
  PROMETHEUS: false
  SKIP_MJD_FILTER: true
  USE_PROFILING: true
METRICS_CONFIG:
  CLASS: apf.metrics.KafkaMetricsProducer
  PARAMS:
    PARAMS:
      bootstrap.servers: b-2-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-1-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-3-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196
      sasl.mechanism: SCRAM-SHA-512
      sasl.password: ztf-ingestionx
      sasl.username: ztf-ingestion
      security.protocol: SASL_SSL
    SCHEMA_PATH: /home/alerce/Desktop/repos2/pipeline/schemas/ingestion_step/metrics.json
    TOPIC: metrics
PYROSCOPE_SERVER: http://pyroscope.pyroscope:4040
DB_CONFIG:
  DB_NAME: alercedb
  HOST: 44.210.122.226
  PASSWORD: AmOeFXXfvzV1rMO
  PORT: 5432
  SCHEMA: multisurvey
  USER: alerce

SCRIBE_ENABLED: false
SCRIBE_PRODUCER_CONFIG:
  CLASS: apf.producers.KafkaSchemalessProducer
  PARAMS:
    bootstrap.servers: b-2-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-1-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196,b-3-public.internalstaging.nwexa4.c16.kafka.us-east-1.amazonaws.com:9196
    sasl.mechanisms: SCRAM-SHA-512
    sasl.password: features_msx
    sasl.username: features_ms
    security.protocol: SASL_SSL
  SCHEMA_PATH: /home/alerce/Desktop/repos2/pipeline/schemas/scribe_step/scribe.avsc
  TOPIC: scribe_multisurvey #este seria el otro topico
SURVEY: lsst
enabled: true
MIN_DETECTIONS_FEATURES: 2