name: Build Production

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    with:
      build-type: production

  alert_archiving_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: alert_archiving_step
      base-folder: alert_archiving_step

  correction_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: correction_step
      base-folder: correction_step
      build-context: .

  early_classification_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: early_classification_step
      base-folder: early_classification_step

  feature_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: feature_step
      step-name-prefix: ""
      base-folder: feature_step

  lc_classification_step_ztf_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_ztf
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-ztf
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_balto_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_balto
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-balto
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_messi_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_messi
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-messi
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_barney_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_barney
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-barney
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_toretto_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_toretto
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-toretto
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lightcurve_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lightcurve_step
      step-name-prefix: ""
      base-folder: lightcurve-step
      build-context: .

  magstats_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: magstats_step
      base-folder: magstats_step
      build-context: .

  prv_candidates_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: prv_candidates_step
      step-name-prefix: ""
      base-folder: prv_candidates_step
      build-context: .

  reflector_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      base-folder: reflector_step
      step-name: reflector_step
      build-type: production

  s3_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: s3_step
      step-name-prefix: ""
      base-folder: s3_step
      build-context: s3_step

  sorting_hat_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: sorting_hat_step
      step-name-prefix: ""
      base-folder: sorting_hat_step
      build-context: .

  watchlist_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: watchlist_step
      base-folder: watchlist_step

  xmatch_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: xmatch_step
      base-folder: xmatch_step

  scribe_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: scribe
      base-folder: scribe
      build-context: .
