name: build_production_image
on:
  release:
    types:
      - published
      - edited
jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/alercebroker/xmatch_step
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
  push_image:
    needs: get_tags
    uses: ./.github/workflows/build.yml
    with:
      tags: ${{ needs.get_tags.outputs.tags }}
    secrets:
      PUBLISH_IMAGE_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
