name: Build Staging

on:
  push:
    branches:
      - main

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    with:
      build-type: staging

  alert_archiving_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: alert_archiving_step
      base-folder: alert_archiving_step
      build-context: alert_archiving_step

  correction_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: correction_step
      step-name-prefix: ""
      base-folder: correction_step
      build-context: .

  early_classification_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: early_classification_step
      base-folder: early_classification_step
      build-context: early_classification_step

  feature_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: feature_step
      step-name-prefix: ""
      base-folder: feature_step
      build-context: feature_step

  lc_classification_step_ztf_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_ztf
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-ztf
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_balto_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_balto
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-balto
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_messi_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_messi
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-messi
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_barney_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_barney
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-barney
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lc_classification_step_toretto_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_toretto
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-toretto
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  lightcurve_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lightcurve_step
      step-name-prefix: ""
      base-folder: lightcurve-step
      build-context: .

  magstats_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: magstats_step
      base-folder: magstats_step
      build-context: .

  prv_candidates_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: prv_candidates_step
      step-name-prefix: ""
      base-folder: prv_candidates_step
      build-context: prv_candidates_step

  reflector_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      base-folder: reflector_step
      build-context: reflector_step
      step-name: reflector_step
      build-type: staging

  s3_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: s3_step
      step-name-prefix: ""
      base-folder: s3_step
      build-context: s3_step

  sorting_hat_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: sorting_hat_step
      step-name-prefix: ""
      base-folder: sorting_hat_step
      build-context: sorting_hat_step

  watchlist_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: watchlist_step
      base-folder: watchlist_step
      build-context: watchlist_step

  xmatch_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: xmatch_step
      step-name-prefix: ""
      base-folder: xmatch_step
      build-context: xmatch_step

  scribe_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: scribe
      step-name-prefix: ""
      base-folder: scribe
      build-context: scribe
