name: Update Versions
on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      git-ref:
        required: false
        type: string
        default: main

jobs:
  update_versions:
    name: Update Versions
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ inputs.build-type }}
      POETRY_HOME: /opt/poetry
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: Install poetry
        run: |
          pip install --upgrade pip
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry
          $POETRY_HOME/bin/poetry --version
      - name: Update version
        run: |
          git config --global user.name "@alerceadmin"
          git config --global user.email "alerceadmin@users.noreply.github.com"
          INITIAL_DIR=$(pwd)
          for i in $(find . -maxdepth 3 -name pyproject.toml)
          do
              if [[ $(dirname $i) == ./libs/P4J ]]; then
                continue
              fi
              if [[ $(dirname $i) == ./libs/mhps ]]; then
                continue
              fi
              echo "$(dirname $i)"
              cd "$(dirname $i)"
              if [[ $BUILD_TYPE == production* ]]; then
                  VERSION=${GITHUB_REF#refs/tags/}
                  $POETRY_HOME/bin/poetry version $VERSION
              else
                  $POETRY_HOME/bin/poetry version prerelease
              fi
              cd $INITIAL_DIR
              git add $i
          done
          git commit -m "chore: update version"
          git push origin ${{ inputs.git-ref }}
